function groupeddata = importfile4(filename, dataLines)
%IMPORTFILE4 Import data from a text file
%  GROUPEDDATA = IMPORTFILE4(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  GROUPEDDATA = IMPORTFILE4(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  groupeddata = importfile4("/Users/Leontanaka/Dropbox/covid-19_proj/proj/grouped_data.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-May-2020 14:45:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "ICUBeds", "TotalPopulation", "PopulationAged60", "PercentofPopulationAged60", "ResidentsAged60PerEachICUBed", "cases", "deaths", "fatal_rate", "state_income"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName1", "EmptyFieldRule", "auto");

% Import the data
groupeddata = readtable(filename, opts);

end